DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(ID INT PRIMARY KEY, NAME VARCHAR(255), AGE INT);
DROP TABLE IF EXISTS MAILS;
CREATE TABLE MAILS(IDHOLDER INT PRIMARY KEY, MAIL VARCHAR(255));
DROP TABLE IF EXISTS PETS;
CREATE TABLE PETS(IDHOLDER INT PRIMARY KEY, TYPE VARCHAR(255), NAME VARCHAR(255));